-- ============================================
-- RESET COMPLETO: Truncar todas las tablas _180
-- Mantiene estructura, borra todos los datos
-- NO borra festivos_es_180 (datos de referencia)
-- ============================================

-- Desactivar temporalmente constraints
SET session_replication_role = 'replica';

TRUNCATE TABLE IF EXISTS calendar_event_mapping_180 CASCADE;
TRUNCATE TABLE IF EXISTS calendar_sync_log_180 CASCADE;
TRUNCATE TABLE IF EXISTS calendar_webhook_180 CASCADE;
TRUNCATE TABLE IF EXISTS empresa_calendar_config_180 CASCADE;
TRUNCATE TABLE IF EXISTS empresa_email_config_180 CASCADE;
TRUNCATE TABLE IF EXISTS contendo_memory_180 CASCADE;
TRUNCATE TABLE IF EXISTS audit_log_180 CASCADE;
TRUNCATE TABLE IF EXISTS envios_email_180 CASCADE;
TRUNCATE TABLE IF EXISTS registroverifactu_180 CASCADE;
TRUNCATE TABLE IF EXISTS lineafactura_180 CASCADE;
TRUNCATE TABLE IF EXISTS factura_180 CASCADE;
TRUNCATE TABLE IF EXISTS auditoria_180 CASCADE;
TRUNCATE TABLE IF EXISTS concepto_180 CASCADE;
TRUNCATE TABLE IF EXISTS iva_180 CASCADE;
TRUNCATE TABLE IF EXISTS emisor_180 CASCADE;
TRUNCATE TABLE IF EXISTS configuracionsistema_180 CASCADE;
TRUNCATE TABLE IF EXISTS work_logs_180 CASCADE;
TRUNCATE TABLE IF EXISTS employee_daily_report_180 CASCADE;
TRUNCATE TABLE IF EXISTS fichajes_180 CASCADE;
TRUNCATE TABLE IF EXISTS ausencias_adjuntos_180 CASCADE;
TRUNCATE TABLE IF EXISTS ausencias_180 CASCADE;
TRUNCATE TABLE IF EXISTS plantilla_bloques_180 CASCADE;
TRUNCATE TABLE IF EXISTS plantilla_dias_180 CASCADE;
TRUNCATE TABLE IF EXISTS empleado_plantillas_180 CASCADE;
TRUNCATE TABLE IF EXISTS asignaciones_plantilla_jornada_180 CASCADE;
TRUNCATE TABLE IF EXISTS plantilla_excepcion_bloques_180 CASCADE;
TRUNCATE TABLE IF EXISTS plantilla_excepciones_180 CASCADE;
TRUNCATE TABLE IF EXISTS plantillas_jornada_180 CASCADE;
TRUNCATE TABLE IF EXISTS jornada_cierre_180 CASCADE;
TRUNCATE TABLE IF EXISTS jornadas_180 CASCADE;
TRUNCATE TABLE IF EXISTS turnos_180 CASCADE;
TRUNCATE TABLE IF EXISTS calendario_empresa_180 CASCADE;
TRUNCATE TABLE IF EXISTS invite_180 CASCADE;
TRUNCATE TABLE IF EXISTS employee_devices_180 CASCADE;
TRUNCATE TABLE IF EXISTS client_tariffs_180 CASCADE;
TRUNCATE TABLE IF EXISTS empleado_clientes_180 CASCADE;
TRUNCATE TABLE IF EXISTS payment_allocations_180 CASCADE;
TRUNCATE TABLE IF EXISTS payment_assignments_180 CASCADE;
TRUNCATE TABLE IF EXISTS payments_180 CASCADE;
TRUNCATE TABLE IF EXISTS clients_180 CASCADE;
TRUNCATE TABLE IF EXISTS storage_180 CASCADE;
TRUNCATE TABLE IF EXISTS perfil_180 CASCADE;
TRUNCATE TABLE IF EXISTS partes_dia_180 CASCADE;
TRUNCATE TABLE IF EXISTS employees_180 CASCADE;
TRUNCATE TABLE IF EXISTS empresa_config_180 CASCADE;
TRUNCATE TABLE IF EXISTS empresa_180 CASCADE;
TRUNCATE TABLE IF EXISTS users_180 CASCADE;

-- Reactivar constraints
SET session_replication_role = 'origin';
